In [2]:
import numpy as np
import random

In [3]:
#number of dimensions
dimensions = 1

#initialization of enviroment
def init_env(size_env):
    env = np.zeros(size_env) #enviroment
    
    for i in range(env.shape[0]):
        for j in range(env.shape[1]):
            env[i,j] = random.randint(0,1)
    return env 

In [4]:
#robot position initialization
def rob_pos_init(dim):
    if( dim[0] == 1):
        rob_pos = np.zeros([1,1])
        rob_pos[0,0] = random.randint(0,int(dim[1])-1)
        return rob_pos
    else:
        rob_pos = np.zeros([1,len(dim)])
        for j in range(0,int(len(dim))):
            rob_pos[0,j] = random.randint(0,int(dim[j])-1)
        return rob_pos

In [5]:
#function check if enviroment is clean
def clean_all(env):
    count = 1
    for i in range(0,env.shape[0]):
        for j in range(0,env.shape[1]):
            count = count * env[i,j]
    return int(count)

In [6]:
def my_robot(env, rob_pos, actuators, t):
    print('env :\n' + str(env))
    n_steps = 1    #number of steps     
    
    names = []
    for a in actuators:
        names.append(a)

    #loop with actions
    while( n_steps <= t):
        if( clean_all(env) == 1 ):
            break;
        if( env[int(rob_pos[0,0]),int(rob_pos[0,1])] == 0):
            env[int(rob_pos[0,0]),int(rob_pos[0,1])] = 1
            print('Suck', end = ' ')
        else:
            r = random.randint(0,len(actuators)-1)
            print(names[r], end=' ')
            for i in range(0, len(actuators[names[r]])):
                rob_pos[0,i] = rob_pos[0,i] + actuators[names[r]][i]
            
            for i in range(0, len(env.shape)):
                if( rob_pos[0,i] < 0 ):
                    rob_pos[0,i] = 0
                elif( rob_pos[0,i] >= env.shape[i] ):
                    rob_pos[0,i] = (env.shape[i] - 1)
        n_steps += 1

In [ ]:
for i in range(2,15):
    print(i)
    my_size = [ i, i ]
    env = init_env(my_size)#np.zeros([1,2])#
    env[0,0] = 1
    rob_pos = rob_pos_init( env.shape )
    actuators = {'left': [0,-1], 'right': [0,1], 'up': [-1,0], 'down': [1,0]}
    t = 1000       #number max of steps
    my_robot( env, rob_pos, actuators, t)
    print('\n'+str(env))

In [7]:
my_size = [ 7, 4 ]
env = init_env(my_size)#np.zeros([1,2])#
env[0,0] = 1
rob_pos = rob_pos_init( env.shape )
actuators = {'left': [0,-1], 'right': [0,1], 'up': [-1,0], 'down': [1,0]}
t = 1000       #number max of steps
my_robot( env, rob_pos, actuators, t)
print('\n'+str(env))

env :
[[1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 0. 1.]]
Suck right down Suck down up left Suck up right left up Suck up left left up left right up right Suck up right down Suck left left right down right left right down Suck down right up up left left right down right right right up down down down left Suck down Suck left down left right right up down up right left right left down left right right left up up down right down right down right down down right left up down up up right down down left left down up Suck up Suck up Suck 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
def init(sizes, value=0):
    if (len(sizes) == 1):
        return [value] * sizes[0]
    else:

        # old code - fixed per comment. This method does not create
        # sizes[0] *new* lists, it just repeats the same list
        # sizes[0] times. This causes unexpected behavior when you
        # try to set an item in a list and all of its siblings get
        # the same change
        # return [init(sizes[1:], value)] * sizes[0]

        # this method works better; it creates a new list each time through
        return [init(sizes[1:], value) for i in range(0,sizes[0])]


In [ ]:
print(init([1,2,3,4,5]))