In [19]:
import numpy as np
import random

In [33]:
#number of dimensions
dimensions = 1

#initialization of enviroment
def init_env(size_env):
    env = np.zeros(size_env) #enviroment
    
#     for i in range(env.shape[0]):
#         for j in range(env.shape[1]):
#             env[i,j] = random.randint(0,1)
    return env 

In [34]:
#robot position initialization
def rob_pos_init(dim):
    if( dim[0] == 1):
        rob_pos = np.zeros([1,1])
        rob_pos[0,0] = random.randint(0,int(dim[1])-1)
        return rob_pos
    else:
        rob_pos = np.zeros([1,len(dim)])
        for j in range(0,int(len(dim))):
            rob_pos[0,j] = random.randint(0,int(dim[j])-1)
        return rob_pos

In [35]:
#function check if enviroment is clean
def clean_all(env):
    count = 1
    for i in range(0,env.shape[0]):
        for j in range(0,env.shape[1]):
            count = count * env[i,j]
    return int(count)

In [85]:
def my_robot(env, rob_pos, actuators, t):
    print('env :\n' + str(env))
    print('pos :\n' + str(rob_pos))
    n_steps = 1    #number of steps     
    
    names = []
    for a in actuators:
        names.append(a)
        #print(actuators[a])

    #loop with actions
    while( n_steps <= t):
        print('init loop: ' + str( rob_pos ));
        if( clean_all(env) == 1 ):
            break;
        if( env[int(rob_pos[0,0]),int(rob_pos[0,1])] == 0):
            env[int(rob_pos[0,0]),int(rob_pos[0,1])] = 1
            print('Suck', end = '\n')
        else:
#             print('Im here')
            r = random.randint(0,len(actuators)-1)
            print(names[r], end='\n')
#             print('prev pos: ' + str(rob_pos))
            for i in range(0, len(actuators[names[r]])):
                rob_pos[0,i] = rob_pos[0,i] + actuators[names[r]][i]
            print('pos: ' + str(rob_pos))
            
            for i in range(0, len(env.shape)):
                print('ii: ' +str(i))
                if( rob_pos[0,i] < 0 ):
                    rob_pos[0,i] = 0
                elif( rob_pos[0,i] >= env.shape[i] ):
                    rob_pos[0,i] = (env.shape[i] - 1)

            print('fix pos: ' + str(rob_pos))
#         print('end loop: ' + str( rob_pos ));
        print( env )
        n_steps += 1

In [86]:
for i in range(4,5):
    print(i)
    my_size = [ 3, i ]
#     print( len(my_size) )
    env = init_env(my_size)#np.zeros([1,2])#
#     print('lenenv ' + str(len(my_size )) + str(len(env.shape)))
#     print('len env ' + str(env.shape[1]) )
    env[0,0] = 1
    rob_pos = rob_pos_init( env.shape )
#     print('init pos: ', str(rob_pos))
    actuators = {'left': [0,-1], 'right': [0,1], 'up': [-1,0], 'down': [1,0]}
#     print('ss:'+str(len(actuators['left'])))
    t = 100       #number max of steps
    my_robot( env, rob_pos, actuators, t)
    print('\n'+str(env))

4
env :
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
pos :
[[1. 1.]]
init loop: [[1. 1.]]
Suck
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
init loop: [[1. 1.]]
left
pos: [[1. 0.]]
ii: 0
ii: 1
fix pos: [[1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
init loop: [[1. 0.]]
Suck
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]]
init loop: [[1. 0.]]
left
pos: [[ 1. -1.]]
ii: 0
ii: 1
fix pos: [[1. 0.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]]
init loop: [[1. 0.]]
down
pos: [[2. 0.]]
ii: 0
ii: 1
fix pos: [[2. 0.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]]
init loop: [[2. 0.]]
Suck
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
init loop: [[2. 0.]]
down
pos: [[3. 0.]]
ii: 0
ii: 1
fix pos: [[2. 0.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
init loop: [[2. 0.]]
down
pos: [[3. 0.]]
ii: 0
ii: 1
fix pos: [[2. 0.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
init loop: [[2. 0.]]
down
pos: [[3. 0.]]
ii: 0
ii: 1
fix pos: [[2. 0.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
init

In [ ]:
def init(sizes, value=0):
    if (len(sizes) == 1):
        return [value] * sizes[0]
    else:

        # old code - fixed per comment. This method does not create
        # sizes[0] *new* lists, it just repeats the same list
        # sizes[0] times. This causes unexpected behavior when you
        # try to set an item in a list and all of its siblings get
        # the same change
        # return [init(sizes[1:], value)] * sizes[0]

        # this method works better; it creates a new list each time through
        return [init(sizes[1:], value) for i in range(0,sizes[0])]


In [ ]:
print(init([1,2,3,4,5]))