In [1]:
import numpy as np
import random

In [2]:
#initialization of enviroment
def init_env(size_env):
    env = np.zeros(size_env) #enviroment
    
    for i in range(env.shape[0]):
        for j in range(env.shape[1]):
            env[i,j] = random.randint(0,1)
    return env 

In [3]:
#robot position initialization
def rob_pos_init(dim):
    if( dim[0] == 1):
        rob_pos = np.zeros([1,1])
        rob_pos[0,0] = random.randint(0,int(dim[1])-1)
        return rob_pos
    else:
        rob_pos = np.zeros([1,len(dim)])
        for j in range(0,int(len(dim))):
            rob_pos[0,j] = random.randint(0,int(dim[j])-1)
        return rob_pos

In [4]:
#function check if enviroment is clean
def clean_all(env):
    count = 1
    for i in range(0,env.shape[0]):
        for j in range(0,env.shape[1]):
            count = count * env[i,j]
    return int(count)

In [5]:
def my_robot(env, rob_pos, actuators, t):
    print('env :\n' + str(env))
    n_steps = 1    #number of steps     
    
    names = []
    for a in actuators:
        names.append(a)

    #loop with actions
    while( n_steps <= t):
        if( clean_all(env) == 1 ):
            break;
        
        if( len(actuators[names[0]]) == 1 ):
            if( env[0,int(rob_pos[0,0])] == 0):
                env[0,int(rob_pos[0,0])] = 1
                print('Suck', end = ' ')
            else:
                r = random.randint(0,1)
#                 print(r)
                rob_pos[0,0] = rob_pos[0,0] + actuators[names[r]][0]
                if( actuators[names[r]][0] == -1 ):
                    print('Left', end = ' ')
                else:
                    print('Right', end = ' ')
                if( rob_pos[0,0] < 0 ):
                    rob_pos[0,0] = 0
                elif( rob_pos[0,0] >= env.shape[1]   ):
                    rob_pos[0,0] = (len(env) - 1)
        else:    
            if( env[int(rob_pos[0,0]),int(rob_pos[0,1])] == 0):
                env[int(rob_pos[0,0]),int(rob_pos[0,1])] = 1
                print('Suck', end = ' ')
            else:
                r = random.randint(0,len(actuators)-1)
                print(names[r], end=' ')
                for i in range(0, len(actuators[names[r]])):
                    rob_pos[0,i] = rob_pos[0,i] + actuators[names[r]][i]

                for i in range(0, len(env.shape)):
                    if( rob_pos[0,i] < 0 ):
                        rob_pos[0,i] = 0
                    elif( rob_pos[0,i] >= env.shape[i] ):
                        rob_pos[0,i] = (env.shape[i] - 1)
        n_steps += 1

In [6]:
for i in range(2,7):
    print(i)
    my_size = [ i, i ]
    env = init_env(my_size)#np.zeros([1,2])#
    env[0,0] = 1
    rob_pos = rob_pos_init( env.shape )
    actuators = {'left': [0,-1], 'right': [0,1], 'up': [-1,0], 'down': [1,0]}
    t = 1000       #number max of steps
    my_robot( env, rob_pos, actuators, t)
    print('\n'+str(env))

2
env :
[[1. 1.]
 [0. 0.]]
Suck left Suck 
[[1. 1.]
 [1. 1.]]
3
env :
[[1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 0.]]
up right left Suck left right right up left down right down Suck left left up Suck 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
4
env :
[[1. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]]
down Suck up left Suck up up Suck up up right Suck up down left right up left down up left right right up down right up right right left down left left up up right up right up right up left up left up right down up right left left left left up up down right up up right down left left left right up up right up up down right up left right right right left up left up left right left down right up up up up up up down down right down left Suck left right right right right left right right up Suck 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
5
env :
[[1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1.]]
down left down up up down up right right Suck

In [10]:
my_size = [ 10, 15 ]
env = init_env(my_size)#np.zeros([1,2])#
env[0,0] = 1
rob_pos = rob_pos_init( env.shape )
actuators = {'left': [0,-1], 'right': [0,1], 'up': [-1,0], 'down': [1,0]}
#actuators = {'left': [-1], 'right': [1]}
t = 1000       #number max of steps
my_robot( env, rob_pos, actuators, t)
print('\n'+str(env))

env :
[[1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1.]
 [0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0.]]
Suck left Suck right left down left Suck down left up Suck right left down down up up left down Suck left Suck left Suck left Suck left up down right left left left up right Suck left right left left Suck down Suck left left left up up Suck right up down down down up left down down right right down up left left left left down left left up up left left down right left left right up right left up down up up down left left left up left right right Suck up Suck left Suck right left up left left left up left up S