In [1]:
import numpy as np
import random

In [2]:
env = np.zeros([1,2])
print(env.shape)

(1, 2)


In [3]:
for i in range(env.shape[0]):
    for j in range(env.shape[1]):
        env[i,j] = random.randint(0,1)
print(env)

[[0. 1.]]


In [4]:
rob_pos = np.zeros([1,2])

for i in range(rob_pos.shape[0]):
    for j in range(rob_pos.shape[1]):
        rob_pos[i,j] = random.randint(0,1)
print(rob_pos)
print(type(int(rob_pos[0,0])))
print(rob_pos[0,1])

[[1. 0.]]
<class 'int'>
0.0


In [5]:
n_steps = 0
t = 1000

def clean_all(env):
    count = 1
    for i in range(0,env.shape[0]):
        for j in range(0,env.shape[1]):
            count = count * env[i,j]
    return int(count)

print(clean_all(env) != 0)

False


In [6]:
while( n_steps < t):
#     print( env[ 0, int(rob_pos[0,1]) ]  )
              
    if( env[0,int(rob_pos[0,1])] != 1):
        env[0,int(rob_pos[0,1])] = 1
        print('Suck', end = ' ')
    else:
        if( rob_pos[0,1] == 0):
            rob_pos[0,1] = 1
            print('Right', end = ' ')
        else:
            rob_pos[0,1] = 0
            print('Left', end = ' ')
    if( clean_all(env) == 1 ):
        break;
    n_steps += 1

Suck 

In [7]:
print(env)
print(clean_all(env) == 1)

[[1. 1.]]
True
