In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

#'sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)'],
iris = pd.read_csv('bezdekIris.data')
iris_data = iris.values
print(iris_data[0:2,:])
print(iris_data.shape)

X = iris_data[:,0:4]
Y = iris_data[:,4]

print(X[45:50,:])
print(Y[45:50])

set_class = {}
set_class = set(set_class)

for i in range(Y.shape[0]):
    set_class.add(Y[i])

print(set_class)

[[4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']]
(149, 5)
[[5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor']
{'Iris-setosa', 'Iris-virginica', 'Iris-versicolor'}


In [2]:
##Testing my K-NN
def my_mse( x1, x2):
    count = 0
    for i in range( 0, x1.shape[0]):
        count += (x1[i] - x2[i])*(x1[i] - x2[i])
    return np.sqrt(count)
#print(my_mse(X[0,:],X[1,:]))

In [3]:
x = X[49,:]
dist = []
K = 5
for i in range(X.shape[0]):
    dist.append( [ i, my_mse( x, X[i,:] ) ] )
dist = np.array(dist)    
dist = dist[dist[:,1].argsort()]
print(dist[0:K,0])

res = []
for r in range(K):
    res.append(Y[int(dist[r,0])])
res = np.array(res)
print(res)

count_set = np.zeros( [ 1, 3] )
cnt = 0

print(set_class)
for i in set_class:
    for r in range(0,K):
        print( i + ' ' + str(r) + ' ' + res[r] )
        if( i == res[r] ):
            count_set[0,cnt] += 1
    print()
    cnt += 1
print(count_set)

[49. 51. 85. 64. 75.]
['Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor']
{'Iris-setosa', 'Iris-virginica', 'Iris-versicolor'}
Iris-setosa 0 Iris-versicolor
Iris-setosa 1 Iris-versicolor
Iris-setosa 2 Iris-versicolor
Iris-setosa 3 Iris-versicolor
Iris-setosa 4 Iris-versicolor

Iris-virginica 0 Iris-versicolor
Iris-virginica 1 Iris-versicolor
Iris-virginica 2 Iris-versicolor
Iris-virginica 3 Iris-versicolor
Iris-virginica 4 Iris-versicolor

Iris-versicolor 0 Iris-versicolor
Iris-versicolor 1 Iris-versicolor
Iris-versicolor 2 Iris-versicolor
Iris-versicolor 3 Iris-versicolor
Iris-versicolor 4 Iris-versicolor

[[0. 0. 5.]]


In [4]:
class_max = np.max(count_set)
print(class_max)

idx_max = 0
for i in range(count_set.shape[0]):
    if( class_max == count_set[0,i] ):
        idx_max = i
print(idx_max)
set_class = list(set_class)
# print(set_class[0])
print(set_class[idx_max])

5.0
0
Iris-setosa
