In [62]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

#'sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)'],
iris = pd.read_csv('bezdekIris.data')
iris_data = iris.values
print(iris_data[0:2,:])
print(iris_data.shape)

X = iris_data[:,0:4]
Y = iris_data[:,4]

print(X[45:50,:])
print(Y[45:50])

[[4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']]
(149, 5)
[[5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor']


In [28]:
##Testing my K-NN
def my_mse( x1, x2):
    count = 0
    for i in range( 0, x1.shape[0]):
        count += (x1[i] - x2[i])*(x1[i] - x2[i])
    return np.sqrt(count)
#print(my_mse(X[0,:],X[1,:]))

0.30000000000000016


In [61]:
x = X[49,:]
dist = []
K = 5
for i in range(X.shape[0]):
    dist.append( [ i, my_mse( x, X[i,:] ) ] )
dist = np.array(dist)    
dist = dist[dist[:,1].argsort()]
print(dist[0:K,0])

res = []
for r in range(K):
    res.append(Y[int(dist[r,0])])
print(res)

[ 49.  51.  85. 140.  64.]
['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor']


In [ ]:
np