In [2]:
#Coded by jecs89
#You can find more in github.com/jecs89
#MLP Step by step 2

import math
import numpy as np

I = np.matrix('0.05; 0.10; 1')
W_IH = np.matrix('0.15 0.30; 0.20 0.35; 0.25 0.40')
W_HO = np.matrix('0.45 0.60; 0.50 0.65; 0.55 0.70')

Y = np.matrix('0.01; 0.99')

print(I, np.shape(I), '\n', W_IH, np.shape(W_IH),'\n', W_HO, np.shape(W_HO),'\n', Y, np.shape(Y))

[[0.05]
 [0.1 ]
 [1.  ]] (3, 1) 
 [[0.15 0.3 ]
 [0.2  0.35]
 [0.25 0.4 ]] (3, 2) 
 [[0.45 0.6 ]
 [0.5  0.65]
 [0.55 0.7 ]] (3, 2) 
 [[0.01]
 [0.99]] (2, 1)


In [3]:
def sig(x):
    return 1.0/(1.0 + np.exp(-x))

In [7]:
H = W_IH.transpose()*I
F_H = sig(H)
print(F_H)

[[0.56893321]
 [0.61063923]]


In [8]:
tmp = np.zeros([3,1])
for i in range(0, np.shape(F_H)[0]):
    tmp[i] = F_H[i]
tmp[2] = 1.0
F_H = tmp
print(F_H)

[[0.56893321]
 [0.61063923]
 [1.        ]]


In [14]:
O = W_HO.transpose()*F_H
F_O = sig(O)
print(F_O)

[[0.75237876]
 [0.80818745]]


In [24]:
print(Y)
Efo = (F_O - Y)
for i in range(0,np.shape(Efo)[0]):
    Efo[i] = Efo[i]*F_O[i]*(1.0-F_O[i])
print(Efo)

[[0.01]
 [0.99]]
[[ 0.13830885]
 [-0.02818467]]


In [71]:
d_ow = np.zeros([3,2])
#print(d_ow)
for j in range(0,2):
    for i in range(0,3):
        if( i != 3 ):
            d_ow[i][j] = F_H[i]
        elif( i == 3 ):
            d_ow[i][j] = 1.0
print(d_ow)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.56893321 0.56893321]
 [0.61063923 0.61063923]
 [1.         1.        ]]


In [39]:
d_E_w_h = np.zeros([2,3])
for j in range(0,3):
    for i in range(0,2):
        d_E_w_h[i][j] = d_ow.transpose()[i][j]*Efo[i]
print(d_E_w_h)
#print(d_ow[0][0]*Efo[0],d_ow[1][0]*Efo[0],d_ow[2][0]*Efo[0])
#print(d_ow[0][0]*Efo[1],d_ow[1][0]*Efo[1],d_ow[2][0]*Efo[1])


[[ 0.0786885   0.08445681  0.13830885]
 [-0.0160352  -0.01721067 -0.02818467]]


In [88]:
Efh = np.zeros([2,1])
for i in range(0,2):
    acum = 0
    for j in range(0,2):
        acum = acum + Efo[j] * W_HO[i,j]
    Efh[i] = acum * F_H[i]*(1.0-F_H[i])
print(Efh)
#print((W_HO[0,0]*Efo[0] + W_HO[0,1]*Efo[1])*F_H[0]*(1.0-F_H[0]))
#print((W_HO[1,0]*Efo[0] + W_HO[1,1]*Efo[1])*F_H[1]*(1.0-F_H[1]))

[[0.01111665]
 [0.01208633]]
[[0.01111665]]
[[0.01208633]]


In [83]:
d_hw = np.zeros([3,2])
#print(d_ow)
for j in range(0,2):
    for i in range(0,3):
        if( i != 3 ):
            d_hw[i][j] = I[i]
        elif( i == 3 ):
            d_ow[i][j] = 1.0
print(d_hw)

[[0.05 0.05]
 [0.1  0.1 ]
 [1.   1.  ]]


In [90]:
d_E_w_i = np.zeros([2,3])
for j in range(0,3):
    for i in range(0,2):
        d_E_w_i[i][j] = d_hw.transpose()[i][j]*Efh[i]
print(d_E_w_i)

[[0.00055583 0.00111167 0.01111665]
 [0.00060432 0.00120863 0.01208633]]


In [94]:
n = 0.1
print( W_HO, '\n\n', W_IH, '\n')
W_HO = W_HO - n * d_E_w_h.transpose()
W_IH = W_IH - n * d_E_w_i.transpose()
print( W_HO, '\n\n', W_IH)

[[0.42639345 0.60481056]
 [0.47466296 0.6551632 ]
 [0.50850735 0.7084554 ]] 

 [[0.14983325 0.29981871]
 [0.1996665  0.34963741]
 [0.246665   0.3963741 ]] 

[[0.4185246  0.60641408]
 [0.46621728 0.65688427]
 [0.49467646 0.71127387]] 

 [[0.14977767 0.29975827]
 [0.19955533 0.34951655]
 [0.24555334 0.39516547]]


In [ ]:
H = W_IH.transpose()*I
F_H = sig(H)
print(F_H)



O = W_HO.transpose()*F_H
F_O = sig(O)
print(F_O)