In [3]:
from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 95%; }
    div#menubar-container     { width: 65%; }
    div#maintoolbar-container { width: 99%; }
</style>
"""))

In [4]:
### author: Josimar Edinson Chire Saire
### NUSP: 10569111
### Curso: SCC5830
### 2019/I
### K-Means

import imageio as igio
import matplotlib.pyplot as plt
import numpy as np
import random

In [40]:
# Filename for the input image I;
# b) Filename for the reference image R;
# c) Option for pixel attributes:
# 1 - R,G,B
# 2 - R,G,B,x,y
# 3 - luminance
# 4 - luminance,x,y
# d) Number of clusters k:
# e) Number of iterations: n
# f) Seed S to be used for the random centroids choice.
# 2. Generate an output image ( ˆI) according to the option for feature extraction.

def dist(c, x):
    acum = 0
    for i in range(0,len(c)):
        acum += np.abs(c[i] - x[i])
    return acum

def function( filename_inp, filename_ref, pixel_att, n_clusters, n_iter, seed ):
    img_inp = igio.imread(filename_inp)
    
    t = 1
    img_shape = img_inp.shape
    m_dist = np.zeros([n_clusters, img_shape[0], img_shape[1]])
    
    threshold = 50
    centroids = np.zeros([n_clusters, 3])
    random.seed( seed )
    
    for c in range(0, n_clusters):
        centroids[c][0] = random.randint(0,img_shape[0])
        centroids[c][1] = random.randint(0,img_shape[1])
        centroids[c][2] = img_inp[int(centroids[c][0]), int(centroids[c][1])]
            
    ##print(centroids)
    
    while( t < 1 ):
        
        for c in range(0, n_clusters):
            for i in range(0, img_shape[0]):
                for j in range(0, img_shape[1]):
                    m_dist[c,i,j] = dist( [centroids[c,0], centroids[c,1], centroids[c,2] ], [i, j, img_inp[i,j] ] )
                    if( m_dist[c,i,j] > threshold ):
                        m_dist[c,i,j] = 0
        
        print(m_dist)
        
        for c in range(0, n_clusters):
            centroids[c][0] = 
            centroids[c][1] = 
            centroids[c][2] = 
                
        t+=1
    
    return img_inp.shape

In [41]:
function("result.png","result.png",1,5,1,1)

[[[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]]

 [[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]]

 [[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... 24. 25. 26.]
  [-1. -1. -1. ... 25. 26. 27.]
  [-1. -1. -1. ... 26. 27. 28.]]

 [[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]]

 [[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]]]


(256, 256)